// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    // // ignore: missing_enum_constant_in_switch
    // switch (defaultTargetPlatform) {
    //   case TargetPlatform.android:
    //     throw UnsupportedError(
    //       'DefaultFirebaseOptions have not been configured for android - '
    //       'you can reconfigure this by running the FlutterFire CLI again.',
    //     );
    //   case TargetPlatform.iOS:
    //     return ios;
    //   case TargetPlatform.macOS:
    //     throw UnsupportedError(
    //       'DefaultFirebaseOptions have not been configured for macos - '
    //       'you can reconfigure this by running the FlutterFire CLI again.',
    //     );
    // }

    // throw UnsupportedError(
    //   'DefaultFirebaseOptions are not supported for this platform.',
    // );
    return ios;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZt8YCsd6JKZwb9eX3oVa3gnJisqsLts',
    appId: '1:552592701771:web:b2d88ad40327f2e03110ce',
    messagingSenderId: '552592701771',
    projectId: 'alertmail-de8ff',
    authDomain: 'alertmail-de8ff.firebaseapp.com',
    storageBucket: 'alertmail-de8ff.appspot.com',
    measurementId: 'G-TPWH26994H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCcSuAVIuF49ZXuPopCT8jR-RN5H4uNw',
    appId: '1:552592701771:ios:3ffc416bd8e639613110ce',
    messagingSenderId: '552592701771',
    projectId: 'alertmail-de8ff',
    storageBucket: 'alertmail-de8ff.appspot.com',
    iosClientId: '552592701771-tmedtdhp0i4a2put41bn05naqu1fjk0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertmail',
  );
}
